import { Layout } from '@/components/Layout';
import { Section, SectionHeader } from '@/components/Section';

export function MaestroPage() {
  return (
    <Layout title="Maestro">
      <Section>
        <SectionHeader
          title="Maestro"
          subtitle="Turns intent into monitored, reversible workflows"
        />

        <div style={{ maxWidth: '800px', margin: '0 auto' }}>
          <p className="text-lg mb-8" style={{ lineHeight: '1.75' }}>
            Maestro is APEX OmniHub's AI-powered workflow orchestration layer that transforms high-level intent
            into fully monitored, reversible workflows. Describe what you want to achieve, and Maestro handles
            the complex orchestration while maintaining complete observability and control.
          </p>

          {/* Value Proposition */}
          <div className="card" style={{ padding: 'var(--space-8)', background: 'linear-gradient(135deg, #0ea5e9 0%, #8b5cf6 100%)', color: 'var(--color-white)', marginBottom: 'var(--space-12)' }}>
            <div style={{ fontSize: 'var(--font-size-sm)', fontWeight: 'var(--font-weight-bold)', letterSpacing: '0.1em', marginBottom: 'var(--space-3)' }}>FROM INTENT TO EXECUTION</div>
            <p style={{ fontSize: 'var(--font-size-lg)', lineHeight: '1.75', margin: 0 }}>
              "When a new customer signs up, create their account in Salesforce, provision their workspace in Slack,
              and send a welcome email." Maestro makes it happen—safely, monitored, and reversible.
            </p>
          </div>

          {/* Core Capabilities */}
          <div style={{ marginTop: 'var(--space-12)' }}>
            <h2 className="heading-2 mb-8">Core Capabilities</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Intent-Based Workflow Generation</h4>
                <p className="text-secondary text-sm mb-4">
                  Describe your business process in natural language. Maestro understands context, identifies
                  required integrations, and generates the appropriate workflow automatically.
                </p>
                <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Natural language workflow definition
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Automatic integration selection
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Context-aware optimization
                  </li>
                </ul>
              </div>

              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Continuous Monitoring</h4>
                <p className="text-secondary text-sm mb-4">
                  Every workflow generated by Maestro includes built-in monitoring and observability.
                  Track execution, identify bottlenecks, and receive alerts when issues arise.
                </p>
                <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Real-time execution tracking
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Performance metrics and SLAs
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Intelligent anomaly detection
                  </li>
                </ul>
              </div>

              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Reversible Execution</h4>
                <p className="text-secondary text-sm mb-4">
                  Maestro automatically generates compensation logic for every workflow. If something goes wrong
                  or you need to roll back, reversal is just a click away.
                </p>
                <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Automatic compensation workflows
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    One-click rollback capability
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    State consistency guarantees
                  </li>
                </ul>
              </div>

              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Intelligent Optimization</h4>
                <p className="text-secondary text-sm mb-4">
                  Maestro learns from execution patterns and continuously optimizes workflows for performance,
                  cost, and reliability without manual intervention.
                </p>
                <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Machine learning-based optimization
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Automatic retry policy tuning
                  </li>
                  <li className="text-secondary text-sm" style={{ paddingLeft: 'var(--space-6)', position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, top: '0.5em', width: '6px', height: '6px', backgroundColor: 'var(--color-accent)', borderRadius: '50%' }}></span>
                    Cost-aware execution planning
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Use Cases */}
          <div style={{ marginTop: 'var(--space-16)' }}>
            <h2 className="heading-2 mb-8">Use Cases</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 'var(--space-6)' }}>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Customer Onboarding</h4>
                <p className="text-secondary text-sm">
                  "When a customer signs up, provision their account across all systems, send welcome materials,
                  and notify the success team." Maestro orchestrates the entire flow.
                </p>
              </div>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Incident Response</h4>
                <p className="text-secondary text-sm">
                  "When an alert fires, create a ticket, notify the on-call engineer, and start diagnostics."
                  Maestro responds instantly with monitored workflows.
                </p>
              </div>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Data Pipeline</h4>
                <p className="text-secondary text-sm">
                  "Extract data from Salesforce, transform it, and load into our warehouse every hour."
                  Maestro handles scheduling, error handling, and monitoring.
                </p>
              </div>
            </div>
          </div>

          {/* How It Works */}
          <div style={{ marginTop: 'var(--space-16)' }}>
            <h2 className="heading-2 mb-8">How It Works</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
              {[
                { step: '1', title: 'Define Intent', desc: 'Describe your business process in natural language or structured format' },
                { step: '2', title: 'Generate Workflow', desc: 'Maestro analyzes requirements and creates an optimized workflow' },
                { step: '3', title: 'Review & Approve', desc: 'Review the generated workflow, make adjustments if needed' },
                { step: '4', title: 'Execute & Monitor', desc: 'Workflow runs with full observability and built-in safety mechanisms' },
                { step: '5', title: 'Learn & Improve', desc: 'Maestro learns from execution and continuously optimizes' }
              ].map(({ step, title, desc }) => (
                <div key={step} className="card" style={{ padding: 'var(--space-5)', display: 'flex', alignItems: 'flex-start', gap: 'var(--space-4)' }}>
                  <div style={{
                    width: '40px',
                    height: '40px',
                    flexShrink: 0,
                    borderRadius: '50%',
                    backgroundColor: 'var(--color-accent)',
                    color: 'var(--color-white)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: 'var(--font-size-lg)',
                    fontWeight: 'var(--font-weight-bold)'
                  }}>
                    {step}
                  </div>
                  <div style={{ flex: 1 }}>
                    <h4 className="heading-4 mb-2">{title}</h4>
                    <p className="text-secondary text-sm">{desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* CTA */}
          <div style={{ marginTop: 'var(--space-16)', textAlign: 'center', padding: 'var(--space-12)', backgroundColor: 'var(--color-surface)', borderRadius: 'var(--border-radius-lg)' }}>
            <h3 className="heading-3 mb-4">Ready to conduct your workflows?</h3>
            <p className="text-secondary mb-8">
              See how Maestro transforms business intent into reliable, monitored workflows.
            </p>
            <a href="/demo.html" className="btn btn--primary">
              Watch Maestro Demo
            </a>
          </div>
        </div>
      </Section>
    </Layout>
  );
}
