import { Layout, Section, SectionHeader, BulletItem, BulletList } from '@/components';

export function MaestroPage() {
  return (
    <Layout title="Maestro">
      <Section>
        <SectionHeader title="Maestro" subtitle="Turns intent into monitored, reversible workflows" />

        <div style={{ maxWidth: '800px', margin: '0 auto' }}>
          <p className="text-lg mb-8" style={{ lineHeight: '1.75' }}>
            Maestro is APEX OmniHub's AI-powered workflow orchestration layer that transforms high-level intent
            into fully monitored, reversible workflows. Describe what you want to achieve, and Maestro handles
            the complex orchestration while maintaining complete observability and control.
          </p>

          <div className="card" style={{ padding: 'var(--space-8)', background: 'linear-gradient(135deg, #0ea5e9 0%, #8b5cf6 100%)', color: 'var(--color-white)', marginBottom: 'var(--space-12)' }}>
            <div style={{ fontSize: 'var(--font-size-sm)', fontWeight: 'var(--font-weight-bold)', letterSpacing: '0.1em', marginBottom: 'var(--space-3)' }}>FROM INTENT TO EXECUTION</div>
            <p style={{ fontSize: 'var(--font-size-lg)', lineHeight: '1.75', margin: 0 }}>
              "When a new customer signs up, create their account in Salesforce, provision their workspace in Slack,
              and send a welcome email." Maestro makes it happen—safely, monitored, and reversible.
            </p>
          </div>

          <div style={{ marginTop: 'var(--space-12)' }}>
            <h2 className="heading-2 mb-8">Core Capabilities</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)' }}>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Intent-Based Workflow Generation</h4>
                <p className="text-secondary text-sm mb-4">
                  Describe your business process in natural language. Maestro understands context, identifies
                  required integrations, and generates the appropriate workflow automatically.
                </p>
                <BulletList>
                  <BulletItem>Natural language workflow definition</BulletItem>
                  <BulletItem>Automatic integration selection</BulletItem>
                  <BulletItem>Context-aware optimization</BulletItem>
                </BulletList>
              </div>

              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Continuous Monitoring</h4>
                <p className="text-secondary text-sm mb-4">
                  Every workflow generated by Maestro includes built-in monitoring and observability.
                  Track execution, identify bottlenecks, and receive alerts when issues arise.
                </p>
                <BulletList>
                  <BulletItem>Real-time execution tracking</BulletItem>
                  <BulletItem>Performance metrics and SLAs</BulletItem>
                  <BulletItem>Intelligent anomaly detection</BulletItem>
                </BulletList>
              </div>

              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Reversible Execution</h4>
                <p className="text-secondary text-sm mb-4">
                  Maestro automatically generates compensation logic for every workflow. If something goes wrong
                  or you need to roll back, reversal is just a click away.
                </p>
                <BulletList>
                  <BulletItem>Automatic compensation workflows</BulletItem>
                  <BulletItem>One-click rollback capability</BulletItem>
                  <BulletItem>State consistency guarantees</BulletItem>
                </BulletList>
              </div>

              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Intelligent Optimization</h4>
                <p className="text-secondary text-sm mb-4">
                  Maestro learns from execution patterns and continuously optimizes workflows for performance,
                  cost, and reliability without manual intervention.
                </p>
                <BulletList>
                  <BulletItem>Machine learning-based optimization</BulletItem>
                  <BulletItem>Automatic retry policy tuning</BulletItem>
                  <BulletItem>Cost-aware execution planning</BulletItem>
                </BulletList>
              </div>
            </div>
          </div>

          <div style={{ marginTop: 'var(--space-16)' }}>
            <h2 className="heading-2 mb-8">Use Cases</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 'var(--space-6)' }}>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Customer Onboarding</h4>
                <p className="text-secondary text-sm">
                  "When a customer signs up, provision their account across all systems, send welcome materials,
                  and notify the success team." Maestro orchestrates the entire flow.
                </p>
              </div>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Incident Response</h4>
                <p className="text-secondary text-sm">
                  "When an alert fires, create a ticket, notify the on-call engineer, and start diagnostics."
                  Maestro responds instantly with monitored workflows.
                </p>
              </div>
              <div className="card" style={{ padding: 'var(--space-6)' }}>
                <h4 className="heading-4 mb-3">Data Pipeline</h4>
                <p className="text-secondary text-sm">
                  "Extract data from Salesforce, transform it, and load into our warehouse every hour."
                  Maestro handles scheduling, error handling, and monitoring.
                </p>
              </div>
            </div>
          </div>

          <div style={{ marginTop: 'var(--space-16)' }}>
            <h2 className="heading-2 mb-8">How It Works</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
              {[
                { step: '1', title: 'Define Intent', desc: 'Describe your business process in natural language or structured format' },
                { step: '2', title: 'Generate Workflow', desc: 'Maestro analyzes requirements and creates an optimized workflow' },
                { step: '3', title: 'Review & Approve', desc: 'Review the generated workflow, make adjustments if needed' },
                { step: '4', title: 'Execute & Monitor', desc: 'Workflow runs with full observability and built-in safety mechanisms' },
                { step: '5', title: 'Learn & Improve', desc: 'Maestro learns from execution and continuously optimizes' }
              ].map(({ step, title, desc }) => (
                <div key={step} className="card" style={{ padding: 'var(--space-5)', display: 'flex', alignItems: 'flex-start', gap: 'var(--space-4)' }}>
                  <div style={{ width: '40px', height: '40px', flexShrink: 0, borderRadius: '50%', backgroundColor: 'var(--color-accent)', color: 'var(--color-white)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 'var(--font-size-lg)', fontWeight: 'var(--font-weight-bold)' }}>{step}</div>
                  <div style={{ flex: 1 }}>
                    <h4 className="heading-4 mb-2">{title}</h4>
                    <p className="text-secondary text-sm">{desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ marginTop: 'var(--space-16)', textAlign: 'center', padding: 'var(--space-12)', backgroundColor: 'var(--color-surface)', borderRadius: 'var(--border-radius-lg)' }}>
            <h3 className="heading-3 mb-4">Ready to conduct your workflows?</h3>
            <p className="text-secondary mb-8">See how Maestro transforms business intent into reliable, monitored workflows.</p>
            <a href="/demo" className="btn btn--primary">Watch Maestro Demo</a>
          </div>
        </div>
      </Section>
    </Layout>
  );
}
