# TruffleHog Configuration
# Exclude documentation and example files from secret scanning

exclude_paths:
  - "**/PRODUCTION_BLOCKERS_ANALYSIS.md"
  - "**/*.example"
  - "**/docs/**"
  - "**/.env.example"
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.md"
  - "**/orchestrator/.env.example"
