/**
 * OmniPort DLQ Type Definitions
 * =============================================================================
 * Type definitions for the Dead Letter Queue (ingress_buffer) table.
 * Used for storing failed ingestion and delivery attempts.
 * =============================================================================
 */

/**
 * DLQ Entry Status
 */
export type DLQStatus = 'pending' | 'replaying' | 'failed';

/**
 * Ingress Buffer Entry (Database Row)
 * Maps directly to the `ingress_buffer` table columns in Supabase.
 */
export interface IngressBufferEntry {
  /** Primary identifier (autogenerated) */
  id?: string;

  /** Correlation ID for distributed tracing */
  correlation_id: string;

  /** The raw input payload that failed processing (stringified JSON) */
  raw_input: string;

  /** Human-readable error reason for debugging */
  error_reason: string;

  /** Processing status (defaults to 'pending') */
  status?: DLQStatus;

  /** Priority score (0-100) */
  risk_score?: number;

  /** Source metadata (e.g., 'omnilink-delivery') */
  source_type?: string;

  /** User ID for RLS */
  user_id?: string | null;

  /** Optional: External reference ID (e.g. event ID) - if supported by schema, otherwise in raw_input */
  // external_ref_id?: string; // Not in current migration
}
